name: Test checks

on: [push, pull_request]

jobs:
    pytest:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            mongodb-version: ["6.0", "7.0", "8.0"]

        env:
          MONGODB_TEST_URL: mongodb://localhost:27017/

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Python3
              uses: actions/setup-python@v4
              with: 
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip3 install -r requirements.txt

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.12.0
              with:
                mongodb-version: ${{ matrix.mongodb-version }}

            - name: Run pytest
              run: |
                pytest
    mypy:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Python3
            uses: actions/setup-python@v4
            with: 
              python-version: '3.12'
          
          - name: Install dependencies
            run: |
              python3 -m pip install --upgrade pip
              pip3 install -r requirements.txt

          - name: Run mypy
            run: |
              mypy src